### ISSUE TITLE
SparkplugNet1.3.8 is not compatible with latest MQTTnet 4.3.6.1152

### ISSUE THREAD

**Issue by simmarn** [SeppPenner/SparkplugNet#99]
Running the Example application with MQTTnet upgraded to 4.3.6.1152 gives the following exception at start.

I need the latest MQTTnet for other projects in the same solution.

An exception occurred: {Exception}, Exception: System.MissingMethodException: Method not found: 'MQTTnet.Client.MqttClientOptionsBuilder MQTTnet.Client.MqttClientOptionsBuilder.WithTcpServer(System.String, System.Nullable`1<Int32>)'.
   at SparkplugNet.Core.Application.SparkplugApplicationBase`1.ConnectInternal()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SparkplugNet.Core.Application.SparkplugApplicationBase`1.ConnectInternal()
   at SparkplugNet.Core.Application.SparkplugApplicationBase`1.Start(SparkplugApplicationOptions applicationOptions)
   at Ermms.Gateway.Sparkplug.SparkplugExample.RunVersionBApplication() in C:\repos\acm\sw\Ermms.Gateway.Sparkplug\Ermms.Gateway.Sparkplug\SparkplugExample.cs:line 149
   at Ermms.Gateway.Sparkplug.SparkplugExample.RunVersionB() in C:\repos\acm\sw\Ermms.Gateway.Sparkplug\Ermms.Gateway.Sparkplug\SparkplugExample.cs:line 109
   at Ermms.Gateway.Sparkplug.SparkplugExample.Start() in C:\repos\acm\sw\Ermms.Gateway.Sparkplug\Ermms.Gateway.Sparkplug\SparkplugExample.cs:line 90
System.MissingMethodException: Method not found: 'MQTTnet.Client.MqttClientOptionsBuilder MQTTnet.Client.MqttClientOptionsBuilder.WithTcpServer(System.String, System.Nullable`1<Int32>)'.
   at SparkplugNet.Core.Application.SparkplugApplicationBase`1.ConnectInternal()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at SparkplugNet.Core.Application.SparkplugApplicationBase`1.ConnectInternal()
   at SparkplugNet.Core.Application.SparkplugApplicationBase`1.Start(SparkplugApplicationOptions applicationOptions)
   at Ermms.Gateway.Sparkplug.SparkplugExample.RunVersionBApplication() in C:\repos\acm\sw\Ermms.Gateway.Sparkplug\Ermms.Gateway.Sparkplug\SparkplugExample.cs:line 149
   at Ermms.Gateway.Sparkplug.SparkplugExample.RunVersionB() in C:\repos\acm\sw\Ermms.Gateway.Sparkplug\Ermms.Gateway.Sparkplug\SparkplugExample.cs:line 109
   at Ermms.Gateway.Sparkplug.SparkplugExample.Start() in C:\repos\acm\sw\Ermms.Gateway.Sparkplug\Ermms.Gateway.Sparkplug\SparkplugExample.cs:line 90

**Comment by SeppPenner** [comment]
Will be done in 1.3.9 (Available soon).
